/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
	{
		name: "blog_category_id",
		label: "Select Blog Category",
		type: "select",
		multiple: false,
		api_end_point: "blog-categories",
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "writer_id",
		label: "Select Writer",
		type: "select",
		multiple: false,
		api_end_point: "blog-writers",
		data_list: [],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "title",
		label: "Enter Title",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "reading_time",
		label: "Enter Reading Time",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "average_rating",
		label: "Enter Average Rating",
		type: "number",
		step: "0.01",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "publish_date",
		label: "Enter Publish Date",
		type: "date",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "scheduled_at",
		label: "Enter Scheduled At",
		type: "datetime-local",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "thumbnail_image",
		label: "Upload Thumbnail Image",
		type: "file",
		multiple: false,
		accept: "image/*",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "gallery",
		label: "Upload Gallery",
		type: "file",
		multiple: true,
		accept: "image/*",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "blog_type",
		label: "Select Blog Type",
		type: "select",
		label: "Select Blog Type",
		multiple: false,
		data_list: [
			{ label: "News", value: "news" },
			{ label: "Tutorial", value: "tutorial" },
			{ label: "Opinion", value: "opinion" },
			{ label: "Review", value: "review" },
			{ label: "Case_study", value: "case_study" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "content_format",
		label: "Select Content Format",
		type: "select",
		label: "Select Content Format",
		multiple: false,
		data_list: [
			{ label: "Article", value: "article" },
			{ label: "Video", value: "video" },
			{ label: "Podcast", value: "podcast" },
			{ label: "Infographic", value: "infographic" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "external_url",
		label: "Enter External Url",
		type: "url",
		placeholder: "https://example.com",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "show_on_top",
		label: "Select Show On Top",
		type: "select",
		label: "Select Show On Top",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "yes" },
			{ label: "No", value: "no" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "allow_comments",
		label: "Select Allow Comments",
		type: "select",
		label: "Select Allow Comments",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "yes" },
			{ label: "No", value: "no" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "is_featured",
		label: "Select Is Featured",
		type: "select",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "1" },
			{ label: "No", value: "0" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "is_published",
		label: "Select Is Published",
		type: "select",
		multiple: false,
		data_list: [
			{ label: "Yes", value: "1" },
			{ label: "No", value: "0" },
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "video_link",
		label: "Enter Video Link",
		type: "url",
		placeholder: "https://example.com",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "meta_title",
		label: "Enter Meta Title",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "short_description",
		label: "Enter Short Description",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-12",
	},
	{
		name: "content",
		label: "Enter Content",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-12",
	},
	{
		name: "meta_description",
		label: "Enter Meta Description",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-12",
	},
	{
		name: "meta_keywords",
		label: "Enter Meta Keywords",
		type: "multichip",
		value: "",
		is_visible: true,
		class: "col-md-12",
	},
];
