/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
  {
    name: "title",
    label: "Enter Title",
    type: "text",
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "blog_category_id",
    label: "Select Blog Category",
    type: "select",
    multiple: false,
    data_list: [],
    value: "",
    is_visible: true,
    class: "col-md-6",
  },

  {
    name: "reading_time",
    label: "Enter Reading Time",
    type: "number",
    step: "1",
    value: "",
    is_visible: false,
    class: "col-md-6",
  },

  {
    name: "publish_date",
    label: "Enter Publish Date",
    type: "datetime-local",
    value: "",
    is_visible: false,
    class: "col-md-6",
  },
  {
    name: "writer",
    label: "Enter Writer",
    type: "number",
    step: "1",
    value: "",
    is_visible: false,
    class: "col-md-6",
  },

  {
    name: "blog_type",
    label: "Select Blog Type",
    type: "select",
    multiple: false,
    data_list: [
      { label: "News", value: "news" },
      { label: "Tutorial", value: "tutorial" },
      { label: "Opinion", value: "opinion" },
    ],
    value: "",
    is_visible: false,
    class: "col-md-6",
  },
  {
    name: "url",
    label: "Enter Url",
    type: "url",
    placeholder: "https://example.com",
    value: "",
    is_visible: false,
    class: "col-md-6",
  },
  {
    name: "show_top",
    label: "Select Show Top",
    type: "select",
    multiple: false,
    data_list: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
    value: "",
    is_visible: true,
    class: "col-md-6",
  },

  {
    name: "video_link",
    label: "Enter Video Link",
    type: "url",
    placeholder: "https://example.com",
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "is_featured",
    label: "Select Is Featured",
    type: "select",
    multiple: false,
    data_list: [
      { label: "Yes", value: "1" },
      { label: "No", value: "0" },
    ],
    value: "",
    is_visible: true,
    class: "col-md-6",
  },

  {
    name: "tags",
    label: "Enter Tags",
    type: "multichip",
    rows: 4,
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "contributors",
    label: "Enter Contributors",
    type: "multichip",
    rows: 6,
    placeholder: "Enter valid JSON",
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "is_published",
    label: "Select Is Published",
    type: "select",
    multiple: false,
    data_list: [
      { label: "Yes", value: "1" },
      { label: "No", value: "0" },
    ],
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "thumbnail_image",
    label: "Upload Thumbnail Image",
    type: "file",
    multiple: false,
    accept: "image/*",
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "images",
    label: "Upload Images",
    type: "file",
    multiple: true,
    accept: "image/*",
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "description",
    label: "Enter Description",
    type: "textarea",
    rows: 4,
    value: "",
    is_visible: true,
    class: "col-md-12",
  },
];
