/**
 * Form Fields Configuration
 * Auto-generated — edit data_list / class / is_visible as needed.
 */

export default [
  {
    name: "category_id",
    label: "Select Category",
    type: "select",
    multiple: false,
    data_list: [
      { label: "Ecommerce", value: "Ecommerce" },
      { label: "Portfolio", value: "Portfolio" },
      { label: "Business", value: "Business" },
      { label: "Others", value: "Others" },
    ],
    value: "",
    is_visible: false,
    class: "col-md-6",
  },
  {
    name: "title",
    label: "Enter Title",
    type: "text",
    value: "",
    is_visible: true,
    class: "col-md-6",
  },

  {
    name: "regular_price",
    label: "Enter Regular Price",
    type: "number",
    step: "0.01",
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "sale_price",
    label: "Enter Sale Price",
    type: "number",
    step: "0.01",
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "demo_url",
    label: "Enter Demo Url",
    type: "url",
    placeholder: "https://example.com",
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "file_path",
    label: "Enter File Path",
    type: "textarea",
    rows: 4,
    value: "",
    is_visible: false,
    class: "col-md-6",
  },
  {
    name: "file_type",
    label: "Enter File Type",
    type: "text",
    value: "",
    is_visible: false,
    class: "col-md-6",
  },
  {
    name: "version",
    label: "Enter Version",
    type: "text",
    value: "",
    is_visible: true,
    class: "col-md-6",
  },

  {
    name: "features",
    label: "Enter Features",
    type: "textarea",
    rows: 4,
    value: "",
    is_visible: false,
    class: "col-md-6",
  },
  {
    name: "features",
    label: "Enter features",
    type: "multichip",
    rows: 4,
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "tags",
    label: "Enter Tags",
    type: "multichip",
    rows: 4,
    value: "",
    is_visible: true,
    class: "col-md-6",
  },

  {
    name: "is_featured",
    label: "Select Is Featured",
    type: "select",
    multiple: false,
    data_list: [
      { label: "Yes", value: "1" },
      { label: "No", value: "0" },
    ],
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "thumbnail_image",
    label: "Upload Thumbnail Image",
    type: "file",
    multiple: false,
    accept: "image/*",
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "gallery_images",
    label: "Upload Gallery Images",
    type: "file",
    multiple: true,
    accept: "image/*",
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "short_description",
    label: "Enter Short Description",
    type: "textarea",
    rows: 4,
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
  {
    name: "description",
    label: "Enter Description",
    type: "textarea",
    rows: 4,
    value: "",
    is_visible: true,
    class: "col-md-6",
  },
];
